### ISSUE TITLE
Does not work in Mendix 7+

### ISSUE THREAD

**Issue by Andy-Fleming** [plamola/mxwidget-tabjumper#1]
Runtime error on web form:
> No constructor found for widget tabjumper.widget.tabjumper

Console error:

> dojo.require and dojo.provide are not supported in Mendix 7. Please, use AMD style for custom widgets. Error: dojo.require and dojo.provide are not supported in Mendix 7. Please, use AMD style for custom widgets.
    at Object.window.dojo.provide.window.dojo.require (http://localhost:8079/mxclientsystem/mxui/mxui.js?636975742383557859:74:214920)
    at http://localhost:8079/widgets/tabjumper/widget/tabjumper.js?636975742383557859:8:6

**Comment by plamola** [comment]
The last thing I did, when I stopped using Mendix as a development platform, was open sourcing the widgets I had developed.

Please consider them as 'abandon'-ware, as I won't be providing updates or fixes.
